language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: supercoderhawk
  password:
    secure: caMnhyKFcCmzqBBWjgkyln0t3feQ8tp+61a7llWNJytgUK8d3xdirq/l2wSP7WsFW4JezSDEtMbpSqWA+L+zO5UOt4tpiD2sVDzDgnpz4/YLxERBQ4k3lEntZt/1XMKUPsahROjr5kEAeQru/bK4unyhHgT+Px67mx0fXmbwi/iSh1pNELsm9qDOPRqGv1m+EtmLSODG6O75xdCk/8Bz5kNX2A6iwR8ktApTEPeH+1vlmM4TeFmCfdJ4K6Iu7GqDuI7ocDy+jemDwIjzbDqAoSQadC4x6l3VRpi91dfI2/wfqGf/J0xg56U/TuCw3uZiR6PW4KWEjFgJHLS8v0+mHLrAOC9cCPWXCljOjja9jpJyR9yf84vgWTNdyhDO6LXmKVauhAJWHHNWHHajXmeo8HStUQsWZfcn8i0Rw5qpX5TbhJWkD7CQK/Zb+yUCbizihZmjkLQJYFMUs1H3Gfx4SpO/Rzqlfk5T2LDG8NMsLWjqvmHF33yGqvlN6wKqlJ50AgH0IXK/DXaiE5vcIXsOaWE36hmrDy2jwoDEkl5DQQgXIg8uSdcaJtydcdn9AcQENc++eE74xxLJKDaZx3Ez7CNOVfchaqAG3Un/SzpTuSAq2iiq5J18aszgRpipVYY1Sl/AiUILbcRNXfYchvFJt+cOZoErl85/bQKIcOwlXy8=
  on:
    tag: true
  skip_existing: true
