language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: supercoderhawk
  password:
    secure: ZeUcO0J8s8clcKcNbTs9O8x/kKMqGbPPK/2hxrHpfPrkHOSSRZceMvnB9hArYg71XviVsUu5JZ5qzbr1pkiXfyj9HCHlI4O9dcBq8WryDHWADjGQmzLRsFI4qOl5+JSugJVYbheCmfEDgdOLhDUsndg39LJ40XUcGht3w1D6lALJh0OWU22CCY/7FDMQ3z513aev5jiZp1i6f/0FMCn2C9clilB2eGtLaAvZJnYVN0q9I0s9GzapkFMs150lY35CiORcN3cMp1D2JUX74sEEUoU1/3oJ1G5KHXFAt3NjE4Txfktqtkps7GJzf7veMoteYdKgXSuAo1hhkLcwd4xcz2IFzG0kxtoY62cNwfpdc+SNbLNiuBpyrVkzoj+5TJK8eHkSX0z6KAfW7IC07RQBFkyRCU8Q5iH3rvjPYRmN2kjMVaETLgieqZW6SamJHToLF+68f7o01nDkaTL+uufIHQXMI/z83UmqBE3Dh7RLZauX6ruoeF2nVoNNXsyPVKatCP33hFwe+v7/f2AxmG7gHf0Pvz/3Lxk4jXIrYdg3KSYa7K4nuqOgILC33HYzCTduHavQreuvsv6k082HP4sfp/HnPPAoWzHqpCGv+7mMBIrnVg3ZwCnq6iIofUbN4fvGROtrNCgLq7QJfPnGLQFedW2EkxCceu16MZLkf1eKh6M=
  on:
    tag: true
  skip_existing: true
