language: python
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
install:
- pip install codecov
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- pytest
after_success:
- codecov
deploy:
- provider: pypi
  user: supercoderhawk
  on:
    tags: true
  skip_existing: true
  password:
    secure: IPohExJi81EvBObpyv1NEvZ8090jMYt6rQBFhBQHxsPpwv0SmUVBdr8DBNOHXVIV58PRDY4Sq6DCKB+AFOPdc164aGtnORc8OU1wF9tR09g6NULelt2t07no7ITEAGh+ukELZXSpJcOfgSViq28y8IXdPjQBVE5ZVgq05/08h+0wEUwJCPF90p29q57uAA722xXQnmRAujpEab9ajF45nNruIpaFtduQ/lGKv1ypqHMp5thRqXoyu8ILryNP8gpjKfWVnNhyce5DLj1OtDHLKOYNKArFaP1976ovsmmVTYwgjzL1QKQsxZejCyZEdDqvdw7sTn5P0clziZUUVJ0T1EMG06YsqceqojB48B7gwElW9bOPrHQKllUfW3okqQtdDeizDiydJ1/y1mOAVz8xRbZYAP4Daj9tbhN2McGSRma3NgqytQjmf8DLM4w6m8HOKLSyDattdwq+KOnChqlgpqPPvgwLJWowmBOmqQAc2V6BMxnamXNXu6v1+iD6ALa97PQkkwYOmQTcgUJ5ccwKz7D7TrJzSkhn9voiYriLUaiZ5KKYoVQ9bNQOOni7EZW+rYIt3tUITl1jdf7X+c3vfj2S1vcBxh7fJtEKVFjlL0W0To/NknVLDA75srSm1YcVJiFOKUBMZFVRBJ6W8wUaReMWkMLmL77q2Y2o0uL8kIM=
- provider: releases
  api_key: "8492ef6fd7bd5b057f0774b35b4a031f09d881ed"
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true
    overwrite: true