language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: supercoderhawk
  password:
    secure: Q1WaUnOiSIGvOblj0eYolAnUJp426sj8hEz98b2UYiFusAGk6uCdeshRvNkHk5I2J1JcLqib0fWRBuHJd/+40V6uxeMgvn7iWyjggcBerIg5N1E781NZf1rElavUJFk9MlDLqx6S3PSUoxMYHXYNAoCdHmyfEYdALHC05/1TA69yxcMZW5thlrINBO6OoD4F65XXKNCnzNtg0SY02SzDdnmAx1MdAyTSVq03QxDV7BmsCMwDJuwuzNMIFx1ugXvbcRWV7pMH6R3IYz/u7WNJYtSjKf60Y8YwKfQeu3WSbbJ4rCOqCWZ+ei3UZphdvAgnODWnzhl6KtzvUAFO71uHPAjSnGTI+xWTqv9xH+hw2tue0hESnFb87/5iLElI3yeEEqO1b9lWgYOM1dRUDBsUSA/HJi9EZx3iRqskcBw5EpWdRasWFrUvlEUn+52lE8fXKc3YkR6P2MdDOZa0KkHKy0HUqi0bLW2HSNAJhgybmhrPvq5lly48h2MZoL634+VJ/6rDd5HTe8FXN7zadj2AjT4SNGCvjZMC4Kmtks+ya+YZeSzPO0sEY908Ojj5cNJoDj27brJw0CfpwGjszGpZVhH1T7qvLFL1nEbpolN/0k2Yt8+M0kPnW6WI7+PGM127+0LAt6yqM8jI1jjbsJI3xo/BzkvCVhYeH57k1Gweq2U=
  on:
    tag: true
  skip_existing: true
